---
- name: Example dynamic inventory
  hosts: "{{ target_hosts }}"

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ec2-user/.ssh/key-performance-test.pem

  tasks:
    - name: Print Name tag
      debug:
        msg: "{{ tags.Name }}"