---
- name: deploy jmeter-client
  hosts: windows

  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates