---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'TestEC2/SG/Key'
  
  Parameters:
  # ------------------------
  # TestLinux用パラメータ
  # ------------------------
    TestLinuxPrivateIP:
      Type: String
      Default: 192.168.10.11
    TestLinuxImageID:
      Type: AWS::SSM::Parameter::Value<String>
      Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    TestLinuxInstanceType:
      Type: String
      Default: t3.micro
    KeyName:
      Type: "AWS::EC2::KeyPair::KeyName"
      Default: "key-performance-test"
    FromIPSegment:
      Type: String
      Default: XXX.XXX.XXX.XXX/32
  # ------------------------
  # TestWin用パラメータ
  # ------------------------
    TestWinPrivateIP:
      Type: String
      Default: 192.168.30.21
    TestWinImageID:
      Type: AWS::SSM::Parameter::Value<String>
      Default: /aws/service/ami-windows-latest/Windows_Server-2019-Japanese-Full-Base
    TestWinInstanceType:
      Type: String
      Default: t3.small

  Resources:
  # ------------------------
  # TestLinux用リソース
  # ------------------------
    TestLinuxSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: sg_testlinux
        GroupDescription: "SG for TestLinux"
        VpcId: !ImportValue VPCID
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref FromIPSegment

    TestLinuxIAMInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Path: "/"
        Roles:
        - !ImportValue EC2IAMRole

    TestLinuxInstance:
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: !Ref TestLinuxImageID
        KeyName: !Ref KeyName
        InstanceType: !Ref TestLinuxInstanceType
        NetworkInterfaces:
          - AssociatePublicIpAddress: "true"
            DeviceIndex: "0"
            SubnetId: !Select [0, !Split [",", !ImportValue PublicSubnetIDs]]
            PrivateIpAddress: !Ref TestLinuxPrivateIP
            GroupSet:
              - !Ref TestLinuxSG
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 8
            DeleteOnTermination: true
        IamInstanceProfile: !Ref TestLinuxIAMInstanceProfile
        UserData:
          Fn::Base64: |
            #!/bin/bash
            sudo yum install -y git
            sudo yum -y install postgresql.x86_64
            sudo amazon-linux-extras enable ansible2
            sudo yum install -y ansible
            sudo ansible-galaxy collection install amazon.aws
            sudo yum install -y python3
            pip3 install boto3
#            sudo yum -y install python-pip
#            pip2 install --use-feature=2020-resolver boto3 botocore

        Tags:
            - Key: Name
              Value: testlinux

  # ------------------------
  # TestLinux用パラメータ
  # ------------------------
    TestWinSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: sg_testwin
        GroupDescription: "SG for TestWin"
        VpcId: !ImportValue VPCID
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 3389
            ToPort: 3389
            SourceSecurityGroupId: !Ref TestLinuxSG

    TestWinIAMInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Path: "/"
        Roles:
        - !ImportValue EC2IAMRole

    TestWinInstance:
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: !Ref TestWinImageID
        KeyName: !Ref KeyName
        InstanceType: !Ref TestWinInstanceType
        NetworkInterfaces:
          - DeviceIndex: "0"
            SubnetId: !Select [0, !Split [",", !ImportValue PrivateSubnetIDs]]
            PrivateIpAddress: !Ref TestWinPrivateIP
            GroupSet:
              - !Ref TestWinSG
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
            DeleteOnTermination: true
        IamInstanceProfile: !Ref TestWinIAMInstanceProfile
        Tags:
            - Key: Name
              Value: testwin


  Outputs:
    TestLinuxSG:
      Value: !Ref TestLinuxSG
      Export:
        Name: TestLinuxSG
    TestWinSG:
      Value: !Ref TestWinSG
      Export:
        Name: TestWinSG