# https://qiita.com/tom-sato/items/e1903cb974fb6c6d5664

# インストール
- name: リポジトリパッケージのインストール
  yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  when: not ansible_check_mode

- name: postgresql12のインストール
  yum:
    name:
      - postgresql12-server
      - python-psycopg2
    state: latest
  when: not ansible_check_mode

# データベースクラスタの作成
- name: クラスタの存在確認
  stat: 
    path: /var/lib/pgsql/12/data/PG_VERSION
  register: dbcluster

- name: initdbの実行
  shell: PGSETUP_INITDB_OPTIONS="-E UTF8 --locale=C" /usr/pgsql-12/bin/postgresql-12-setup initdb
  when: not dbcluster.stat.exists

# 設定ファイルの配置
- name: .pgsql_profileの配置
  copy:
    src: ../files/.pgsql_profile
    dest: /var/lib/pgsql/.pgsql_profile
    owner: postgres
    group: postgres
    mode: 0700

- name: .pgsql_profileの反映
  shell: source /var/lib/pgsql/.pgsql_profile

- name: /var/lib/pgsql/12/data/postgresql.confの配置
  copy:
    src: ../files/postgresql.conf
    dest: /var/lib/pgsql/12/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: pg_hba.confの配置
  copy:
    src: ../files/pg_hba.conf
    dest: /var/lib/pgsql/12/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

# ファイアウォール設定
- name: firewalldでTCP5432を許可
  firewalld: permanent=True service=postgresql state=enabled immediate=true

# サービス起動
- name: サービスの起動
  service: name=postgresql-12 state=restarted enabled=yes


# データベース・ユーザの作成
- name : create database
  postgresql_db:
    name: "tourreserve"
    encoding: "UTF-8"
    login_user: postgres
  become_user: postgres
  become: yes
  when: not ansible_check_mode

- name: create user
  postgresql_user: 
    db: "tourreserve"
    name: "appuser"
    password: "password"
    priv: ALL
    state: present
    login_user: postgres
  become_user: postgres
  become: yes
  when: not ansible_check_mode
