CREATE or REPLACE PROCEDURE PROC1 ()
AS $$
DECLARE
  i INT; 
BEGIN
  DELETE FROM TOURCON;
  DELETE FROM TOURINFO;
  DELETE FROM ACCOMMODATION;
  i := 1;
  FOR i IN 1..8000 LOOP
	INSERT INTO ACCOMMODATION (ACCOM_CODE, ACCOM_NAME, ACCOM_TEL) VALUES (TO_CHAR(i, 'FM0000'), ('TERASOLUNAホテル'||TO_CHAR(i, 'FM0000')), '012-123-4567');
  END LOOP;
END;
$$
LANGUAGE plpgsql;

CALL PROC1();
